name: Build and Test

on:
  push:
    branches:
      - v4
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.repository == 'ke1-dotcom/oc-wiki'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pages: write      # Thêm dòng này
      id-token: write   # Thêm dòng này
