name: Build and Test
on:
  push:
    branches:
      - v4
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: official-stockera/quartz-gh-pages-action@v1
